version: '3.8'
services:

  app:
    build: .
    container_name: app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - migrations:/code/migrations/versions
    expose:
      - 8000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}
    restart: always

  postgres:
    build: postgres/.
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/sql:/docker-entrypoint-initdb.d
      - ./postgres/configs:/configs
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 6379
    restart: always


volumes:
  postgres_data:
  migrations:
