version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/scripts/sql:/docker-entrypoint-initdb.d
      - ./postgres/configs:/configs
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    restart: always


volumes:
  grafana_data:
  loki_data:
  postgres_data:
  migrations:
  photos:
  certificates: